version: '3'

services:
   db:
      image: postgres:16.0
      restart: on-failure
      ports:
         - '${DB_PORT}:${DB_PORT}'
      environment:
         POSTGRES_PASSWORD: ${DB_PASSWORD}
         POSTGRES_DB: ${DB_DATABASE}
      container_name: ${DB_CONTAINER_NAME}
      volumes:
         - ./postgres:/var/lib/postgresql/data
